### PR TITLE
Upgrade and switch to Drone 1.0.0

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by techknowlogick** [comment]
Is this repo still active? My understanding was that the repo moved to: https://github.com/drone/drone-git

**Comment by bradrydzewski** [comment]
true, this repo has been replaced with `drone/git`. Maybe we want to archive it?

**Comment by tboerger** [comment]
But this plugin is still used by 0.8? done/drone-git is pushing to drone/git, right?

**Comment by tboerger** [comment]
Still merging it for now as it just migrates the build infrastructure to proper multiarch and cloud.drone.io.

**Pull request merged**
