### PR TITLE
Checkout branch before checking out the commit to preserve the original

### LINKED ISSUE #26: Preserve original branch the commit checked out is from
Branch in build environment is always "master", even if that wasn't the branch that triggered the build. Scripts that case behavior based on branch or otherwise introspect the git repository state are broken by this behavior.

### PR DESCRIPTION
**Pull request by Franklin89**
fixes #26

### CODE REVIEW

**Review by tonglil — COMMENTED** [review]
How does this work?
Checking out a specific commit does not check out the branch, and actually leaves you in a detached state.
Any clarity will help in reviewing this PR.
Thanks!

**Comment by Franklin89** [comment]
@tonglil You are correct. You will end up in detached mode. I was using `gitversion`to check the branch that I was on (also I need gitversion for automatic versioning). If you `reset` the branch will stay master and not be in detached mode. `gitversion` will then still say master branch instead of test for example. If you use checkout it will be on `test` branch. 

Example using `git checkout`:
git checkout

Example using `git reset`:
git reset

**Comment by tonglil** [comment]
Thanks, but I still do not understand what the goal of this change is yet.

**Comment by Franklin89** [comment]
This way the commit gets properly detached. Try it out on your console. If you use reset things get messy on the master branch imho.

**Review by tboerger — APPROVED** [review]
I'm not against that, but let's see what @bradrydzewski thinks about this change

**Review by tboerger — CHANGES_REQUESTED** [review]
Nope, last commit is not ok for me. We are not building the docker images like that, it's up to drone to build the binaries for the plugins.

**Comment by tboerger** [comment]
Replaced by drone/drone-git repository, closing this issue.

**Pull request closed without merging**
