### PR TITLE
Added git --global flag to remapSubmodule to support multi-level recursive HTTPS …

### PR DESCRIPTION
**Pull request by jpzk**
…checkout (more than one level)

I needed to add this and use it to get a successful checkout of recursive submodules using overwrites of the submodule url. The current version (drone-plugins/drone-git master) only support one level of private submodule checkouts. The corresponding test only checks that. I am not a go programmer, so extending the test would take me a lot of time.

### CODE REVIEW

**Comment by Bugagazavr** [comment]
LGTM

**Comment by donny-dont** [comment]
Seems fine to me. Any potential side effects here? Always kinda cautious when touching a core plugin.

**Comment by bradrydzewski** [comment]
LGTM

@donny-dont we should be good here. I have this covered in the unit tests and also this will really only impact a small subset of drone users that do submodule mapping in the yaml. But thanks for double-checking!

**Comment by donny-dont** [comment]
:confetti_ball:

**Comment by bradrydzewski** [comment]
sorry, I should have noticed sooner but this PR needs to be made against the `release/0.5-alt` branch (random I know) but that is the current active branch. I'll switch to master later today, but in the meantime that is where the change needs to be made

**Comment by jpzk** [comment]
https://github.com/drone-plugins/drone-git/pull/30 :+1:

**Pull request merged**
