### PR TITLE
read env-file from PLUGIN_ENV_FILE env var

### PR DESCRIPTION
**Pull request by rvora**
We should be able to read an env_file in the clone step

```
- name: detect_pullrequest
  image: alpine
  commands:
      - echo "DRONE_BUILD_EVENT=pull_request" >> .env_file
      - echo "DRONE_COMMIT_REF=refs/pull-requests/1/from" >> .env_file

- name: pullrequest_clone
  image: drone/git
  settings:
      env_file: .env_file
  depends_on:
      - detect_pullrequest
```

### CODE REVIEW

**Comment by techknowlogick** [comment]
The repo that is used in v1.0.0 of drone is https://github.com/drone/drone-git you may want to open this PR there.

**Comment by donny-dont** [comment]
We're moving away from loading an environment file. You're free to fork a plugin and use that as your custom clone step. You can also just call git directly in a step too if that's something you want to do.

**Comment by rvora** [comment]
So what is the recommended way to pass results from one step to the next
step. I thought env-file is an elegant way to do that.

Rajul Vora
(408) 877-6581

**Comment by bradrydzewski** [comment]
the reason we removed `.env` files from most of the plugins is because it is an added attack surface that circumvents some of our protections for public projects such as signing the yaml, preventing modification to plugin parameters. Using an environment file to modify plugins is ok for private projects, but we need to consider both public and private projects.

**Comment by tboerger** [comment]
For mentioned reasons we are getting rid of the env files. But we encourage forking plugins to properly match your specific needs.

**Comment by bradrydzewski** [comment]
@tboerger thinking about this, we could make environment variable files opt-in:

```
- name: foo
  image: plugins/foo
  settings:
    from_env: path/to/file
```

since this is opt-in and configured in the yaml, the yaml could be signed to prevent the security concerns I mentioned previously.

**Comment by rvora** [comment]
I like that. There needs to be an official way to pass information from
step to step within a pipeline and from git repo itself.

I can see how it can be useful in a CD pipeline where each branch or
directory of gitrepo is for a target environment needing different
environment variables. Very much the pattern if you are implementing Gitops.

Rajul Vora - typos by Android

**Pull request closed without merging**
