### PR TITLE
Remove default --depth. Fixes #15.

### LINKED ISSUE #15: Remove default depth
There should be no default depth. See https://github.com/drone-plugins/drone-git/pull/14

### PR DESCRIPTION
**Pull request by gregory90**
Let me know if I should change something:)

### CODE REVIEW

**Comment by tboerger** [comment]
I'm fine with the change, but I'm not sure if that breaks the builds of some people that rely on the default.

**Comment by gregory90** [comment]
I was following directions in https://github.com/drone-plugins/drone-git/pull/14. If something has changed in that matter I will be happy to change default --depth back to 50.

**Comment by bradrydzewski** [comment]
LGTM

**Comment by gregory90** [comment]
Thanks! Could you restart build? There were some errors in pushing image to registry http://beta.drone.io/drone-plugins/drone-git/53

**Comment by gregory90** [comment]
@bradrydzewski Sorry for bothering you so much, but there are still some errors - with coverage plugin this time
```
[info] Pulling image plugins/drone-coverage:latest
Drone Coverage Plugin built from 7627e50
Parsing coverage file /drone/src/github.com/drone-plugins/drone-git/coverage.out
Cannot submit coverage. Cannot save build 53. meddler.Insert: DB error in Exec: Error 1062: Duplicate entry '53-1' for key 'build_number'
[info] build failed (exit code 1)
```

**Comment by tboerger** [comment]
We need a new commit :D

**Comment by gregory90** [comment]
Should I make new pull request?

**Pull request merged**
